name: Feature Request
description: Suggest a new feature or improvement for the Hytale Server Egg
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the information below.

  - type: dropdown
    id: panel
    attributes:
      label: Panel Type
      description: Which panel does this feature apply to?
      options:
        - Both Pelican and Pterodactyl
        - Pelican Panel only
        - Pterodactyl Panel only
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New configuration option
        - New server functionality
        - Installation improvement
        - Documentation improvement
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? Why do you need it?
      placeholder: Explain the problem or use case...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have an idea of how this could be implemented, describe it here.
      placeholder: Describe your proposed solution...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to make sure this feature hasn't already been requested
          required: true
